"""File names used in the project."""

INTRODUCTION_FILENAME = "introduction.mp3"
SEGMENT_FILENAME_TEMPLATE = "segment_{i}.mp3"
CLOSING_FILENAME = "closing.mp3"
MUSIC_FILENAME = "music.mp3"
COMPOSITE_FILENAME = "composite.mp3"
VIDEO_BACKGROUND_FILENAME = "background.png"
VIDEO_PREIMAGE_WITH_TEXT_FILENAME = "preimage_with_text.png"
FINAL_VIDEO_FILENAME = "final_video.mp4"
INTRO_WITH_FADE_FILENAME = "introduction_with_fades.mp3"
OUTRO_WITH_FADE_FILENAME = "outro_with_fades.mp3"
TIMESTAMPS_FILENAME = "timestamps.txt"
MASTER_DIRECTORY_NAME = "master"

EPISODE_OUTLINE_FILENAME = "episode_outline.json"
EPISODE_SCRIPT_FILENAME = "episode_script.json"
SCRIPTURE_INSIGHTS_FILENAME = "scripture_insights.json"
VIDEO_DESCRIPTION_FILENAME = "video_description.txt"
TRANSCRIPT_FILENAME = "transcript.txt"
