repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-json
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
    exclude: package.lock.json
- repo: local
  hooks:
    - id: pyright
      name: pyright
      entry: pyright
      language: system
      types_or: [python, pyi, jupyter]
    - id: Ruff check
      name: Ruff check
      entry: ruff
      language: system
      types_or: [python, pyi, jupyter]
      args: [check, --fix]
    - id: Ruff format
      name: Ruff format
      entry: ruff
      language: system
      types_or: [python, pyi, jupyter]
      args: [format]
